{% set name = "progressbar33" %}
{% set version = "2.4" %}
{% set sha256 = "51fe0d9b3b4023db2f983eeccdfc8c9846b84db8443b9bee002c7f58f4376eff" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - progressbar

about:
  home: http://github.com/germangh/python-progressbar
  license: GNU Library or LGPL or BSD
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'Text progress bar library for Python.'

extra:
  recipe-maintainers:
    - npavlovikj
